<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SuperSimpleTcp" Version="3.1.0" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Tcp\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="KeysStrokerLib">
      <HintPath>..\libs\KeysStrokerLib.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
