<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>iconApp.ico</ApplicationIcon>
    <PackageIcon>iconApp.ico</PackageIcon>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="iconApp.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\iconApp.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspose.PDF" Version="25.10.0" />
    <PackageReference Include="Aspose.Words" Version="25.10.0" />
    <PackageReference Include="DinkToPdf" Version="1.0.8" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
    <PackageReference Include="DocX" Version="5.0.0" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="IoTClient" Version="1.0.48" />
    <PackageReference Include="Microsoft.Playwright" Version="1.55.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3595.46" />
    <PackageReference Include="NReco.PdfGenerator" Version="1.2.1" />
    <PackageReference Include="PDFsharp" Version="6.2.2" />
    <PackageReference Include="S7netplus" Version="0.20.0" />
    <PackageReference Include="Select.HtmlToPdf" Version="26.3.0" />
    <PackageReference Include="SSH.NET" Version="2025.0.0" />
    <PackageReference Include="SuperSimpleTcp" Version="3.1.0" />
    <PackageReference Include="System.Management" Version="10.0.4" />
    <PackageReference Include="UglyToad.MakeMe" Version="0.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\API\API.csproj" />
    <ProjectReference Include="..\iSoft.DatabaseServer\iSoft.DatabaseServer.csproj" />
    <ProjectReference Include="..\iSoft.Database\iSoft.Database.csproj" />
    <ProjectReference Include="..\iSoft.RabbitMq\iSoft.RabbitMq.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="KeysStrokerLib">
      <HintPath>..\libs\KeysStrokerLib.dll</HintPath>
    </Reference>
    <Reference Include="PrintHpHelper">
      <HintPath>PrintHpHelper\PrintHpHelper.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update=".env">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update=".env - prod dev">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update=".env - Copy %282%29">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update=".env - prod">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update=".env - dev">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Font\Roboto-Italic-VariableFont_wdth,wght.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Font\Roboto-VariableFont_wdth,wght.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Font\Seven Segment.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Resources\close_app.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Connection.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Disconnection.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\HSFBackGround.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\HSFBG.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\HSFLogo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\HSFLogo1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\icon_logo_app.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="Resources\Menu1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Menu2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Menu3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Printer.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Template\NgoaiVi.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Template\NoiVi.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Template\Table.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Template\TableSumary.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>